In [275]:
import pandas as pd

In [276]:
url = '/content/vendas_online_pandas.csv'

In [277]:
dados = pd.read_csv(url, sep = ';')

In [278]:
dados.head()

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,05/01/2024,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,"R$ 3.500,00",Cartão de Crédito,Concluída,5.0
1,05/01/2024,Carlos Lima,carlos.lima@email.com,Mouse Logitech,Acessórios,Santiago,RS,2,"R$ 89,90",Pix,Concluída,4.0
2,06/01/2024,Juliana Alves,juliana.alves@email.com,Teclado Mecânico,Acessórios,Porto Alegre,RS,1,"R$ 249,90",Boleto,Cancelada,NaN
3,06/01/2024,Marcos Pereira,marcos.p@email.com,Monitor LG 24,Eletrônicos,Florianópolis,SC,1,"R$ 899,00",Cartão de Crédito,Concluída,5.0
4,07/01/2024,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,"R$ 1.299,90",Pix,Concluída,5.0

In [279]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_venda       32 non-null     object
 1   cliente          32 non-null     object
 2   email            32 non-null     object
 3   produto          32 non-null     object
 4   categoria        32 non-null     object
 5   cidade           32 non-null     object
 6   estado           32 non-null     object
 7   quantidade       32 non-null     int64
 8   preco_unitario   32 non-null     object
 9   forma_pagamento  32 non-null     object
 10  status           32 non-null     object
 11  avaliacao        27 non-null     float64
dtypes: float64(1), int64(1), object(10)
memory usage: 3.1+ KB

In [280]:
dados['data_venda'] = pd.to_datetime(dados['data_venda'], format = '%d/%m/%Y')

In [281]:
dados['data_venda'] = dados['data_venda'].astype('datetime64[ns]')

In [282]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_venda       32 non-null     datetime64[ns]
 1   cliente          32 non-null     object
 2   email            32 non-null     object
 3   produto          32 non-null     object
 4   categoria        32 non-null     object
 5   cidade           32 non-null     object
 6   estado           32 non-null     object
 7   quantidade       32 non-null     int64
 8   preco_unitario   32 non-null     object
 9   forma_pagamento  32 non-null     object
 10  status           32 non-null     object
 11  avaliacao        27 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(9)
memory usage: 3.1+ KB

In [283]:
dados['preco_unitario'] = dados['preco_unitario'].apply(lambda x: x.replace('R$', '').replace('.', '').replace(',', '.').strip()).astype(float)

In [284]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_venda       32 non-null     datetime64[ns]
 1   cliente          32 non-null     object
 2   email            32 non-null     object
 3   produto          32 non-null     object
 4   categoria        32 non-null     object
 5   cidade           32 non-null     object
 6   estado           32 non-null     object
 7   quantidade       32 non-null     int64
 8   preco_unitario   32 non-null     float64
 9   forma_pagamento  32 non-null     object
 10  status           32 non-null     object
 11  avaliacao        27 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 3.1+ KB

In [285]:
dados.head()

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,2024-01-05,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,3500.0,Cartão de Crédito,Concluída,5.0
1,2024-01-05,Carlos Lima,carlos.lima@email.com,Mouse Logitech,Acessórios,Santiago,RS,2,89.9,Pix,Concluída,4.0
2,2024-01-06,Juliana Alves,juliana.alves@email.com,Teclado Mecânico,Acessórios,Porto Alegre,RS,1,249.9,Boleto,Cancelada,NaN
3,2024-01-06,Marcos Pereira,marcos.p@email.com,Monitor LG 24,Eletrônicos,Florianópolis,SC,1,899.0,Cartão de Crédito,Concluída,5.0
4,2024-01-07,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,1299.9,Pix,Concluída,5.0

In [286]:
dados['forma_pagamento'] = dados['forma_pagamento'].str.lower().str.strip()

In [287]:
dados['status'] = dados['status'].str.lower().str.strip()

In [288]:
dados.head()

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,2024-01-05,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,3500.0,cartão de crédito,concluída,5.0
1,2024-01-05,Carlos Lima,carlos.lima@email.com,Mouse Logitech,Acessórios,Santiago,RS,2,89.9,pix,concluída,4.0
2,2024-01-06,Juliana Alves,juliana.alves@email.com,Teclado Mecânico,Acessórios,Porto Alegre,RS,1,249.9,boleto,cancelada,NaN
3,2024-01-06,Marcos Pereira,marcos.p@email.com,Monitor LG 24,Eletrônicos,Florianópolis,SC,1,899.0,cartão de crédito,concluída,5.0
4,2024-01-07,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,1299.9,pix,concluída,5.0

In [289]:
dados.isnull().sum()

data_venda         0
cliente            0
email              0
produto            0
categoria          0
cidade             0
estado             0
quantidade         0
preco_unitario     0
forma_pagamento    0
status             0
avaliacao          5
dtype: int64

In [290]:
dados_avaliados = dados.dropna(subset = ['avaliacao'])

In [291]:
dados.isnull().sum()

data_venda         0
cliente            0
email              0
produto            0
categoria          0
cidade             0
estado             0
quantidade         0
preco_unitario     0
forma_pagamento    0
status             0
avaliacao          5
dtype: int64

In [292]:
faturamento = dados['quantidade'] * dados['preco_unitario']

In [293]:
vendas_concluidas = dados.query('status == "concluída"')

In [294]:
vendas_concluidas

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,2024-01-05,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,3500.0,cartão de crédito,concluída,5.0
1,2024-01-05,Carlos Lima,carlos.lima@email.com,Mouse Logitech,Acessórios,Santiago,RS,2,89.9,pix,concluída,4.0
3,2024-01-06,Marcos Pereira,marcos.p@email.com,Monitor LG 24,Eletrônicos,Florianópolis,SC,1,899.0,cartão de crédito,concluída,5.0
4,2024-01-07,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,1299.9,pix,concluída,5.0
5,2024-01-07,Pedro Martins,pedro.m@email.com,Headset HyperX,Acessórios,São Paulo,SP,1,349.9,cartão de crédito,concluída,4.0
6,2024-01-08,Amanda Costa,amanda.costa@email.com,Smartphone Samsung,Eletrônicos,Rio de Janeiro,RJ,1,2199.0,cartão de crédito,concluída,5.0
7,2024-01-08,Rafael Torres,rafael.t@email.com,Mesa Escritório,Móveis,Santa Maria,RS,1,499.9,pix,concluída,4.0
8,2024-01-09,Fernanda Rocha,fernanda.r@email.com,Webcam Full HD,Acessórios,Santiago,RS,2,159.9,boleto,concluída,3.0
9,2024-01-09,Lucas Andrade,lucas.a@email.com,Notebook Lenovo,Eletrônicos,Curitiba,PR,1,4200.0,cartão de crédito,concluída,5.0
10,2024-01-10,Camila Nunes,camila.n@email.com,SSD 1TB Kingston,Hardware,São Paulo,SP,2,399.9,pix,concluída,4.0
11,2024-01-10,João Pedro,joao.p@email.com,Memória RAM 16GB,Hardware,Florianópolis,SC,2,279.9,cartão de crédito,concluída,4.0
12,2024-01-11,Laura Mendes,laura.m@email.com,Impressora Epson,Eletrônicos,Porto Alegre,RS,1,749.9,boleto,concluída,4.0
13,2024-01-11,Gustavo Silva,gustavo.s@email.com,Cabo HDMI,Acessórios,Rio de Janeiro,RJ,3,39.9,pix,concluída,5.0
15,2024-01-12,Diego Ramos,diego.r@email.com,Suporte Monitor,Móveis,São Paulo,SP,1,189.9,pix,concluída,4.0
16,2024-01-13,Patrícia Gomes,patricia.g@email.com,Notebook Dell Inspiron,Eletrônicos,Florianópolis,SC,1,3500.0,cartão de crédito,concluída,5.0
17,2024-01-13,André Oliveira,andre.o@email.com,Mouse Logitech,Acessórios,Santa Maria,RS,1,89.9,pix,concluída,3.0
18,2024-01-14,Vanessa Dias,vanessa.d@email.com,Smart TV 43,Eletrônicos,Rio de Janeiro,RJ,1,2299.9,cartão de crédito,concluída,5.0
20,2024-01-15,Carolina Ribeiro,carolina.r@email.com,Teclado Mecânico,Acessórios,Curitiba,PR,1,249.9,pix,concluída,4.0
21,2024-01-15,Felipe Moraes,felipe.m@email.com,Placa de Vídeo RTX 4060,Hardware,São Paulo,SP,1,2899.9,cartão de crédito,concluída,5.0
22,2024-01-16,Larissa Freitas,larissa.f@email.com,Cadeira Gamer,Móveis,Porto Alegre,RS,1,1299.9,cartão de crédito,concluída,4.0
24,2024-01-17,Sofia Cardoso,sofia.c@email.com,Monitor LG 24,Eletrônicos,Santa Maria,RS,2,899.0,cartão de crédito,concluída,5.0
25,2024-01-17,Mateus Barbosa,mateus.b@email.com,SSD 1TB Kingston,Hardware,Rio de Janeiro,RJ,1,399.9,pix,concluída,4.0
26,2024-01-18,Helena Castro,helena.c@email.com,Smartphone Samsung,Eletrônicos,São Paulo,SP,1,2199.0,boleto,concluída,4.0
28,2024-01-19,Mariana Teixeira,mariana.t@email.com,Notebook Lenovo,Eletrônicos,Santiago,RS,1,4200.0,cartão de crédito,concluída,5.0
29,2024-01-19,Thiago Martins,thiago.m@email.com,Headset HyperX,Acessórios,Porto Alegre,RS,2,349.9,pix,concluída,4.0
30,2024-01-20,Aline Moreira,aline.m@email.com,Smart TV 43,Eletrônicos,Florianópolis,SC,1,2299.9,cartão de crédito,concluída,5.0
31,2024-01-20,Ricardo Reis,ricardo.r@email.com,Cabo HDMI,Acessórios,Santa Maria,RS,5,39.9,pix,concluída,4.0

In [295]:
dados['status'].unique()

array(['concluída', 'cancelada', 'pendente'], dtype=object)

In [296]:
vendas_canceladas = dados.query('status == "cancelada"')

In [297]:
vendas_canceladas

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
2,2024-01-06,Juliana Alves,juliana.alves@email.com,Teclado Mecânico,Acessórios,Porto Alegre,RS,1,249.9,boleto,cancelada,NaN
14,2024-01-12,Isabela Ferreira,isabela.f@email.com,Tablet Samsung,Eletrônicos,Curitiba,PR,1,1599.0,cartão de crédito,cancelada,NaN
23,2024-01-16,Eduardo Lopes,eduardo.l@email.com,Webcam Full HD,Acessórios,Florianópolis,SC,1,159.9,pix,cancelada,NaN

In [298]:
vendas_pendentes = dados.query('status == "pendente"')

In [299]:
vendas_pendentes

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
19,2024-01-14,Bruno Almeida,bruno.a@email.com,HD Externo 2TB,Hardware,Santiago,RS,1,459.9,boleto,pendente,NaN
27,2024-01-18,Rodrigo Lima,rodrigo.l@email.com,Mesa Escritório,Móveis,Curitiba,PR,1,499.9,pix,pendente,NaN

In [300]:
vendas_acima_1000 = dados.query('preco_unitario > 1000')

In [301]:
vendas_acima_1000

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,2024-01-05,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,3500.0,cartão de crédito,concluída,5.0
4,2024-01-07,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,1299.9,pix,concluída,5.0
6,2024-01-08,Amanda Costa,amanda.costa@email.com,Smartphone Samsung,Eletrônicos,Rio de Janeiro,RJ,1,2199.0,cartão de crédito,concluída,5.0
9,2024-01-09,Lucas Andrade,lucas.a@email.com,Notebook Lenovo,Eletrônicos,Curitiba,PR,1,4200.0,cartão de crédito,concluída,5.0
14,2024-01-12,Isabela Ferreira,isabela.f@email.com,Tablet Samsung,Eletrônicos,Curitiba,PR,1,1599.0,cartão de crédito,cancelada,NaN
16,2024-01-13,Patrícia Gomes,patricia.g@email.com,Notebook Dell Inspiron,Eletrônicos,Florianópolis,SC,1,3500.0,cartão de crédito,concluída,5.0
18,2024-01-14,Vanessa Dias,vanessa.d@email.com,Smart TV 43,Eletrônicos,Rio de Janeiro,RJ,1,2299.9,cartão de crédito,concluída,5.0
21,2024-01-15,Felipe Moraes,felipe.m@email.com,Placa de Vídeo RTX 4060,Hardware,São Paulo,SP,1,2899.9,cartão de crédito,concluída,5.0
22,2024-01-16,Larissa Freitas,larissa.f@email.com,Cadeira Gamer,Móveis,Porto Alegre,RS,1,1299.9,cartão de crédito,concluída,4.0
26,2024-01-18,Helena Castro,helena.c@email.com,Smartphone Samsung,Eletrônicos,São Paulo,SP,1,2199.0,boleto,concluída,4.0
28,2024-01-19,Mariana Teixeira,mariana.t@email.com,Notebook Lenovo,Eletrônicos,Santiago,RS,1,4200.0,cartão de crédito,concluída,5.0
30,2024-01-20,Aline Moreira,aline.m@email.com,Smart TV 43,Eletrônicos,Florianópolis,SC,1,2299.9,cartão de crédito,concluída,5.0

In [302]:
#VENDAS POR CATEGORIA

In [303]:
dados['categoria'].unique()

array(['Eletrônicos', 'Acessórios', 'Móveis', 'Hardware'], dtype=object)

In [304]:
vendas_eletronicos = dados.query('categoria == "Eletrônicos"')

In [305]:
vendas_eletronicos

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,2024-01-05,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,3500.0,cartão de crédito,concluída,5.0
3,2024-01-06,Marcos Pereira,marcos.p@email.com,Monitor LG 24,Eletrônicos,Florianópolis,SC,1,899.0,cartão de crédito,concluída,5.0
6,2024-01-08,Amanda Costa,amanda.costa@email.com,Smartphone Samsung,Eletrônicos,Rio de Janeiro,RJ,1,2199.0,cartão de crédito,concluída,5.0
9,2024-01-09,Lucas Andrade,lucas.a@email.com,Notebook Lenovo,Eletrônicos,Curitiba,PR,1,4200.0,cartão de crédito,concluída,5.0
12,2024-01-11,Laura Mendes,laura.m@email.com,Impressora Epson,Eletrônicos,Porto Alegre,RS,1,749.9,boleto,concluída,4.0
14,2024-01-12,Isabela Ferreira,isabela.f@email.com,Tablet Samsung,Eletrônicos,Curitiba,PR,1,1599.0,cartão de crédito,cancelada,NaN
16,2024-01-13,Patrícia Gomes,patricia.g@email.com,Notebook Dell Inspiron,Eletrônicos,Florianópolis,SC,1,3500.0,cartão de crédito,concluída,5.0
18,2024-01-14,Vanessa Dias,vanessa.d@email.com,Smart TV 43,Eletrônicos,Rio de Janeiro,RJ,1,2299.9,cartão de crédito,concluída,5.0
24,2024-01-17,Sofia Cardoso,sofia.c@email.com,Monitor LG 24,Eletrônicos,Santa Maria,RS,2,899.0,cartão de crédito,concluída,5.0
26,2024-01-18,Helena Castro,helena.c@email.com,Smartphone Samsung,Eletrônicos,São Paulo,SP,1,2199.0,boleto,concluída,4.0
28,2024-01-19,Mariana Teixeira,mariana.t@email.com,Notebook Lenovo,Eletrônicos,Santiago,RS,1,4200.0,cartão de crédito,concluída,5.0
30,2024-01-20,Aline Moreira,aline.m@email.com,Smart TV 43,Eletrônicos,Florianópolis,SC,1,2299.9,cartão de crédito,concluída,5.0

In [306]:
vendas_acessorios = dados.query('categoria == "Acessórios"')

In [307]:
vendas_acessorios

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
1,2024-01-05,Carlos Lima,carlos.lima@email.com,Mouse Logitech,Acessórios,Santiago,RS,2,89.9,pix,concluída,4.0
2,2024-01-06,Juliana Alves,juliana.alves@email.com,Teclado Mecânico,Acessórios,Porto Alegre,RS,1,249.9,boleto,cancelada,NaN
5,2024-01-07,Pedro Martins,pedro.m@email.com,Headset HyperX,Acessórios,São Paulo,SP,1,349.9,cartão de crédito,concluída,4.0
8,2024-01-09,Fernanda Rocha,fernanda.r@email.com,Webcam Full HD,Acessórios,Santiago,RS,2,159.9,boleto,concluída,3.0
13,2024-01-11,Gustavo Silva,gustavo.s@email.com,Cabo HDMI,Acessórios,Rio de Janeiro,RJ,3,39.9,pix,concluída,5.0
17,2024-01-13,André Oliveira,andre.o@email.com,Mouse Logitech,Acessórios,Santa Maria,RS,1,89.9,pix,concluída,3.0
20,2024-01-15,Carolina Ribeiro,carolina.r@email.com,Teclado Mecânico,Acessórios,Curitiba,PR,1,249.9,pix,concluída,4.0
23,2024-01-16,Eduardo Lopes,eduardo.l@email.com,Webcam Full HD,Acessórios,Florianópolis,SC,1,159.9,pix,cancelada,NaN
29,2024-01-19,Thiago Martins,thiago.m@email.com,Headset HyperX,Acessórios,Porto Alegre,RS,2,349.9,pix,concluída,4.0
31,2024-01-20,Ricardo Reis,ricardo.r@email.com,Cabo HDMI,Acessórios,Santa Maria,RS,5,39.9,pix,concluída,4.0

In [308]:
vendas_moveis = dados.query('categoria == "Móveis"')

In [309]:
vendas_moveis

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
4,2024-01-07,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,1299.9,pix,concluída,5.0
7,2024-01-08,Rafael Torres,rafael.t@email.com,Mesa Escritório,Móveis,Santa Maria,RS,1,499.9,pix,concluída,4.0
15,2024-01-12,Diego Ramos,diego.r@email.com,Suporte Monitor,Móveis,São Paulo,SP,1,189.9,pix,concluída,4.0
22,2024-01-16,Larissa Freitas,larissa.f@email.com,Cadeira Gamer,Móveis,Porto Alegre,RS,1,1299.9,cartão de crédito,concluída,4.0
27,2024-01-18,Rodrigo Lima,rodrigo.l@email.com,Mesa Escritório,Móveis,Curitiba,PR,1,499.9,pix,pendente,NaN

In [310]:
vendas_hardware = dados.query('categoria == "Hardware"')

In [311]:
vendas_hardware

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
10,2024-01-10,Camila Nunes,camila.n@email.com,SSD 1TB Kingston,Hardware,São Paulo,SP,2,399.9,pix,concluída,4.0
11,2024-01-10,João Pedro,joao.p@email.com,Memória RAM 16GB,Hardware,Florianópolis,SC,2,279.9,cartão de crédito,concluída,4.0
19,2024-01-14,Bruno Almeida,bruno.a@email.com,HD Externo 2TB,Hardware,Santiago,RS,1,459.9,boleto,pendente,NaN
21,2024-01-15,Felipe Moraes,felipe.m@email.com,Placa de Vídeo RTX 4060,Hardware,São Paulo,SP,1,2899.9,cartão de crédito,concluída,5.0
25,2024-01-17,Mateus Barbosa,mateus.b@email.com,SSD 1TB Kingston,Hardware,Rio de Janeiro,RJ,1,399.9,pix,concluída,4.0

In [312]:
#VENDAS POR ESTADO

In [313]:
dados['estado'].unique()

array(['RS', 'SC', 'PR', 'SP', 'RJ'], dtype=object)

In [314]:
vendas_rs = dados.query('estado == "RS"')

In [315]:
vendas_rs

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
0,2024-01-05,Ana Souza,ana.souza@email.com,Notebook Dell Inspiron,Eletrônicos,Santa Maria,RS,1,3500.0,cartão de crédito,concluída,5.0
1,2024-01-05,Carlos Lima,carlos.lima@email.com,Mouse Logitech,Acessórios,Santiago,RS,2,89.9,pix,concluída,4.0
2,2024-01-06,Juliana Alves,juliana.alves@email.com,Teclado Mecânico,Acessórios,Porto Alegre,RS,1,249.9,boleto,cancelada,NaN
7,2024-01-08,Rafael Torres,rafael.t@email.com,Mesa Escritório,Móveis,Santa Maria,RS,1,499.9,pix,concluída,4.0
8,2024-01-09,Fernanda Rocha,fernanda.r@email.com,Webcam Full HD,Acessórios,Santiago,RS,2,159.9,boleto,concluída,3.0
12,2024-01-11,Laura Mendes,laura.m@email.com,Impressora Epson,Eletrônicos,Porto Alegre,RS,1,749.9,boleto,concluída,4.0
17,2024-01-13,André Oliveira,andre.o@email.com,Mouse Logitech,Acessórios,Santa Maria,RS,1,89.9,pix,concluída,3.0
19,2024-01-14,Bruno Almeida,bruno.a@email.com,HD Externo 2TB,Hardware,Santiago,RS,1,459.9,boleto,pendente,NaN
22,2024-01-16,Larissa Freitas,larissa.f@email.com,Cadeira Gamer,Móveis,Porto Alegre,RS,1,1299.9,cartão de crédito,concluída,4.0
24,2024-01-17,Sofia Cardoso,sofia.c@email.com,Monitor LG 24,Eletrônicos,Santa Maria,RS,2,899.0,cartão de crédito,concluída,5.0
28,2024-01-19,Mariana Teixeira,mariana.t@email.com,Notebook Lenovo,Eletrônicos,Santiago,RS,1,4200.0,cartão de crédito,concluída,5.0
29,2024-01-19,Thiago Martins,thiago.m@email.com,Headset HyperX,Acessórios,Porto Alegre,RS,2,349.9,pix,concluída,4.0
31,2024-01-20,Ricardo Reis,ricardo.r@email.com,Cabo HDMI,Acessórios,Santa Maria,RS,5,39.9,pix,concluída,4.0

In [316]:
vendas_sc = dados.query('estado == "SC"')

In [317]:
vendas_sc

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
3,2024-01-06,Marcos Pereira,marcos.p@email.com,Monitor LG 24,Eletrônicos,Florianópolis,SC,1,899.0,cartão de crédito,concluída,5.0
11,2024-01-10,João Pedro,joao.p@email.com,Memória RAM 16GB,Hardware,Florianópolis,SC,2,279.9,cartão de crédito,concluída,4.0
16,2024-01-13,Patrícia Gomes,patricia.g@email.com,Notebook Dell Inspiron,Eletrônicos,Florianópolis,SC,1,3500.0,cartão de crédito,concluída,5.0
23,2024-01-16,Eduardo Lopes,eduardo.l@email.com,Webcam Full HD,Acessórios,Florianópolis,SC,1,159.9,pix,cancelada,NaN
30,2024-01-20,Aline Moreira,aline.m@email.com,Smart TV 43,Eletrônicos,Florianópolis,SC,1,2299.9,cartão de crédito,concluída,5.0

In [318]:
vendas_pr = dados.query('estado == "PR"')

In [319]:
vendas_pr

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
4,2024-01-07,Beatriz Santos,bia.santos@email.com,Cadeira Gamer,Móveis,Curitiba,PR,1,1299.9,pix,concluída,5.0
9,2024-01-09,Lucas Andrade,lucas.a@email.com,Notebook Lenovo,Eletrônicos,Curitiba,PR,1,4200.0,cartão de crédito,concluída,5.0
14,2024-01-12,Isabela Ferreira,isabela.f@email.com,Tablet Samsung,Eletrônicos,Curitiba,PR,1,1599.0,cartão de crédito,cancelada,NaN
20,2024-01-15,Carolina Ribeiro,carolina.r@email.com,Teclado Mecânico,Acessórios,Curitiba,PR,1,249.9,pix,concluída,4.0
27,2024-01-18,Rodrigo Lima,rodrigo.l@email.com,Mesa Escritório,Móveis,Curitiba,PR,1,499.9,pix,pendente,NaN

In [320]:
vendas_sp = dados.query('estado == "SP"')

In [321]:
vendas_sp

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
5,2024-01-07,Pedro Martins,pedro.m@email.com,Headset HyperX,Acessórios,São Paulo,SP,1,349.9,cartão de crédito,concluída,4.0
10,2024-01-10,Camila Nunes,camila.n@email.com,SSD 1TB Kingston,Hardware,São Paulo,SP,2,399.9,pix,concluída,4.0
15,2024-01-12,Diego Ramos,diego.r@email.com,Suporte Monitor,Móveis,São Paulo,SP,1,189.9,pix,concluída,4.0
21,2024-01-15,Felipe Moraes,felipe.m@email.com,Placa de Vídeo RTX 4060,Hardware,São Paulo,SP,1,2899.9,cartão de crédito,concluída,5.0
26,2024-01-18,Helena Castro,helena.c@email.com,Smartphone Samsung,Eletrônicos,São Paulo,SP,1,2199.0,boleto,concluída,4.0

In [322]:
vendas_rj = dados.query('estado == "RJ"')

In [323]:
vendas_rj

,data_venda,cliente,email,produto,categoria,cidade,estado,quantidade,preco_unitario,forma_pagamento,status,avaliacao
6,2024-01-08,Amanda Costa,amanda.costa@email.com,Smartphone Samsung,Eletrônicos,Rio de Janeiro,RJ,1,2199.0,cartão de crédito,concluída,5.0
13,2024-01-11,Gustavo Silva,gustavo.s@email.com,Cabo HDMI,Acessórios,Rio de Janeiro,RJ,3,39.9,pix,concluída,5.0
18,2024-01-14,Vanessa Dias,vanessa.d@email.com,Smart TV 43,Eletrônicos,Rio de Janeiro,RJ,1,2299.9,cartão de crédito,concluída,5.0
25,2024-01-17,Mateus Barbosa,mateus.b@email.com,SSD 1TB Kingston,Hardware,Rio de Janeiro,RJ,1,399.9,pix,concluída,4.0

In [324]:
dados['faturamento'] = dados['quantidade'] * dados['preco_unitario']

In [325]:
dados.groupby('categoria')['faturamento'].sum().sort_values(ascending = False)

categoria
Eletrônicos    29443.7
Hardware        5119.3
Móveis          3789.5
Acessórios      2618.1
Name: faturamento, dtype: float64

In [326]:
dados.groupby('cliente')['faturamento'].sum().sort_values(ascending = False)

cliente
Lucas Andrade       4200.0
Mariana Teixeira    4200.0
Ana Souza           3500.0
Patrícia Gomes      3500.0
Felipe Moraes       2899.9
Vanessa Dias        2299.9
Aline Moreira       2299.9
Amanda Costa        2199.0
Helena Castro       2199.0
Sofia Cardoso       1798.0
Isabela Ferreira    1599.0
Larissa Freitas     1299.9
Beatriz Santos      1299.9
Marcos Pereira       899.0
Camila Nunes         799.8
Laura Mendes         749.9
Thiago Martins       699.8
João Pedro           559.8
Rafael Torres        499.9
Rodrigo Lima         499.9
Bruno Almeida        459.9
Mateus Barbosa       399.9
Pedro Martins        349.9
Fernanda Rocha       319.8
Juliana Alves        249.9
Carolina Ribeiro     249.9
Ricardo Reis         199.5
Diego Ramos          189.9
Carlos Lima          179.8
Eduardo Lopes        159.9
Gustavo Silva        119.7
André Oliveira        89.9
Name: faturamento, dtype: float64

In [327]:
dados.groupby('produto')['quantidade'].sum().sort_values(ascending = False)

produto
Cabo HDMI                  8
Monitor LG 24              3
Headset HyperX             3
Webcam Full HD             3
SSD 1TB Kingston           3
Mouse Logitech             3
Cadeira Gamer              2
Teclado Mecânico           2
Mesa Escritório            2
Notebook Dell Inspiron     2
Memória RAM 16GB           2
Smartphone Samsung         2
Notebook Lenovo            2
Smart TV 43                2
HD Externo 2TB             1
Impressora Epson           1
Placa de Vídeo RTX 4060    1
Tablet Samsung             1
Suporte Monitor            1
Name: quantidade, dtype: int64

In [328]:
dados.groupby('forma_pagamento')['quantidade'].mean()

forma_pagamento
boleto               1.200000
cartão de crédito    1.142857
pix                  1.692308
Name: quantidade, dtype: float64

In [329]:
dados.groupby('estado')['faturamento'].sum().sort_values(ascending = False)

estado
RS    14246.3
PR     7848.7
SC     7418.6
SP     6438.5
RJ     5018.5
Name: faturamento, dtype: float64

In [330]:
dados.groupby('cidade')['faturamento'].max().sort_values(ascending = False)

cidade
Curitiba          4200.0
Santiago          4200.0
Florianópolis     3500.0
Santa Maria       3500.0
São Paulo         2899.9
Rio de Janeiro    2299.9
Porto Alegre      1299.9
Name: faturamento, dtype: float64

In [331]:
dados['mes'] = dados['data_venda'].dt.month

In [332]:
dados.groupby('mes')['quantidade'].sum()

mes
1    44
Name: quantidade, dtype: int64

In [333]:
dados.groupby('cliente')['quantidade'].sum().sort_values(ascending = False).head(5)

cliente
Ricardo Reis      5
Gustavo Silva     3
Fernanda Rocha    2
Camila Nunes      2
Thiago Martins    2
Name: quantidade, dtype: int64

In [334]:
dados.groupby('produto')['quantidade'].sum().sort_values(ascending = False).head(5)

produto
Cabo HDMI           8
Monitor LG 24       3
Headset HyperX      3
Webcam Full HD      3
SSD 1TB Kingston    3
Name: quantidade, dtype: int64

In [335]:
dados.groupby('categoria')['faturamento'].sum().sort_values(ascending = False).head(3)

categoria
Eletrônicos    29443.7
Hardware        5119.3
Móveis          3789.5
Name: faturamento, dtype: float64

In [336]:
dados.groupby('cidade')['quantidade'].sum().sort_values(ascending=False).head(3)

cidade
Santa Maria       10
Rio de Janeiro     6
Florianópolis      6
Name: quantidade, dtype: int64

In [337]:
import os

In [338]:
os.makedirs('resultados/filtros', exist_ok=True)

In [339]:
filtros = {
    'vendas_concluidas': dados.query('status == "concluida"'),
    'vendas_canceladas': dados.query('status == "cancelada"'),
    'vendas_pendentes': dados.query('status == "pendente"'),
    'vendas_acima_1000': dados.query('faturamento > 1000'),
    'vendas_pix': dados.query('forma_pagamento == "pix"'),
    'vendas_cartao': dados.query('forma_pagamento == "cartao"'),
    'vendas_boleto': dados.query('forma_pagamento == "boleto"'),
    'vendas_rs': dados.query('estado == "RS"')
}

In [341]:
for nome_arquivo, filtro in filtros.items():
    filtro.to_csv(f'resultados/filtros/{nome_arquivo}.csv', index=False)

In [343]:
os.listdir('resultados/filtros')

['vendas_pendentes.csv',
 'vendas_acima_1000.csv',
 'vendas_cartao.csv',
 'vendas_rs.csv',
 'vendas_canceladas.csv',
 'vendas_pix.csv',
 'vendas_concluidas.csv',
 'vendas_boleto.csv']